# Default values for opa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openpolicyagent/opa
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.64.1"

service:
  type: NodePort
  port: 8181

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: opa.airflow.cluster
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# # Additional volumes on the output Deployment definition.
# volumes: #[]
# # - name: foo
# #   secret:
# #     secretName: mysecret
# #     optional: false
#   - name: example-policy
#     configMap:
#       name: example-policy
#   - name: policy-administrative-roles
#     configMap:
#       name: policy-administrative-roles

# # Additional volumeMounts on the output Deployment definition.
# volumeMounts: #[]
# # - name: foo
# #   mountPath: "/etc/foo"
# #   readOnly: true
#   - readOnly: true
#     mountPath: /policies
#     name: example-policy
#   - readOnly: true
#     mountPath: /policies
#     name: policy-administrative-roles

policies:
  - policy-administrative-roles
  - example-policy
