apiVersion: v1
data:
  policy-administrative-roles.rego: |-
    package iam

    import rego.v1

    default allow := false
    admin_count := count(has_admin)
    owner_count := count(has_owner)

    allow if {
        count(has_admin) == 0
        count(has_owner) == 0
    }

    has_admin contains r if {
      some r in input.bindings
      contains(r.role, "Admin")
    }

    has_owner contains r if {
      some r in input.bindings
      contains(r.role, "Owner")
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: policy-administrative-roles
