kind: Service
apiVersion: v1
metadata:
  name: opa
  labels:
    app: opa
spec:
  type: {{ .Values.service.type }}
  selector:
    app: opa
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}